---
- name: Setup tomcat
  hosts: all
  become: true
  tasks:
  - name: install java on redhat
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"

  - name: install java on ubuntu
    apt:
      name: default-jdk
      state: present
    when: ansible_os_family == "Debian"

  - name: download tomcat package
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.65/bin/apache-tomcat-9.0.65.tar.gz
      dest: /opt

  - name: Extract file
    unarchive:
      src: /opt/apache-tomcat-9.0.65.tar.gz
      dest: /opt/
      remote_src: true 

  - name: adding execute permissions
    file:
      path: /opt/apache-tomcat-9.0.65/bin/startup.sh
      mode: 0777

  - name: start tomcat service
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-9.0.65/bin

